# sweep_config.yaml
name: my_model_sweep
method: grid
project: oracle-v1
metric:
  name: test_loss
  goal: minimize

parameters:
  batch_size:
    values: [ 16 ]
  epochs:
    values: [ 10 ]
  num_layers:
    values: [ 2, 4, 6 ]
  n_heads:
    values: [ 4, 8 ]
  embed_dim:
    values: [ 128, 256 ]
  p3:
    values: [ 0.4, 0.6 ]
  dropout:
    values: [ 0.05, 0.15 ]

command:
  - ${env}
  - python
  - -m
  - scripts.model_training.insee_train
