# sweep_config.yaml
name: my_model_sweep
method: random
project: oracle-v1
metric:
  name: test_loss
  goal: minimize

parameters:
  batch_size:
    values: [ 32 ]
  epochs:
    values: [ 50 ]
  num_layers:
    values: [ 2, 3, 4 ]
  n_heads:
    values: [ 2, 4, 8 ]
  embed_dim:
    values: [ 32, 64, 128 ]
  p3:
    distribution: uniform
    min: 0.2
    max: 0.4
  dropout:
    distribution: uniform
    min: 0.05
    max: 0.12
  pool_heads:
    values: [ 2, 4, 8 ]
  p3_max:
    distribution: uniform
    min: 0.6
    max: 0.9


command:
  - ${env}
  - python
  - -m
  - scripts.model_training.insee_train
